interface MockData {
  id: number;
  date: string;
  execTime: string;
  spread: string;
  side: string;
  qty: number;
  symbol: string;
  price: number;
  posEffect: string;
  edit: null;
  delete: null;
}

export const TRADE_MOCK_DATA: MockData[] = [
  {
    id: 1,
    date: '08/26/2021',
    execTime: '16:15:00',
    spread: 'Stock',
    side: 'long',
    qty: 709,
    symbol: 'ATVI',
    price: 25.45,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 2,
    date: '12/02/2019',
    execTime: '16:29:02',
    spread: 'Stock',
    side: 'long',
    qty: 885,
    symbol: 'ATVI',
    price: 59.54,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 3,
    date: '12/17/2019',
    execTime: '2:15:27',
    spread: 'Stock',
    side: 'long',
    qty: 186,
    symbol: 'ATVI',
    price: 77.06,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 4,
    date: '05/25/2020',
    execTime: '15:29:46',
    spread: 'Stock',
    side: 'long',
    qty: 586,
    symbol: 'ATVI',
    price: 26.84,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 5,
    date: '08/03/2021',
    execTime: '21:18:48',
    spread: 'Stock',
    side: 'long',
    qty: 532,
    symbol: 'ATVI',
    price: 17.77,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 6,
    date: '12/27/2019',
    execTime: '11:21:39',
    spread: 'Stock',
    side: 'long',
    qty: 230,
    symbol: 'ATVI',
    price: 12.62,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 7,
    date: '04/07/2021',
    execTime: '23:48:34',
    spread: 'Stock',
    side: 'long',
    qty: 458,
    symbol: 'ATVI',
    price: 67.86,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 8,
    date: '02/01/2021',
    execTime: '8:00:26',
    spread: 'Stock',
    side: 'long',
    qty: 93,
    symbol: 'ATVI',
    price: 83.71,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 9,
    date: '12/20/2020',
    execTime: '7:23:51',
    spread: 'Stock',
    side: 'long',
    qty: 138,
    symbol: 'ATVI',
    price: 97.72,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 10,
    date: '12/12/2020',
    execTime: '11:58:26',
    spread: 'Stock',
    side: 'long',
    qty: 581,
    symbol: 'ATVI',
    price: 50.74,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 11,
    date: '08/31/2019',
    execTime: '13:08:03',
    spread: 'Stock',
    side: 'long',
    qty: 398,
    symbol: 'ATVI',
    price: 67.32,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 12,
    date: '08/27/2021',
    execTime: '20:41:07',
    spread: 'Stock',
    side: 'long',
    qty: 59,
    symbol: 'ATVI',
    price: 76.52,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 13,
    date: '03/08/2021',
    execTime: '15:18:05',
    spread: 'Stock',
    side: 'long',
    qty: 978,
    symbol: 'ATVI',
    price: 90.94,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 14,
    date: '03/25/2020',
    execTime: '5:27:16',
    spread: 'Stock',
    side: 'long',
    qty: 892,
    symbol: 'ATVI',
    price: 23.59,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 15,
    date: '09/25/2020',
    execTime: '10:37:55',
    spread: 'Stock',
    side: 'long',
    qty: 202,
    symbol: 'ATVI',
    price: 50.68,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 16,
    date: '01/18/2021',
    execTime: '19:20:30',
    spread: 'Stock',
    side: 'long',
    qty: 532,
    symbol: 'ATVI',
    price: 70.05,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 17,
    date: '10/24/2020',
    execTime: '3:05:33',
    spread: 'Stock',
    side: 'long',
    qty: 573,
    symbol: 'ATVI',
    price: 93.32,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 18,
    date: '10/03/2021',
    execTime: '10:12:52',
    spread: 'Stock',
    side: 'long',
    qty: 554,
    symbol: 'ATVI',
    price: 33.09,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 19,
    date: '04/30/2021',
    execTime: '7:52:02',
    spread: 'Stock',
    side: 'long',
    qty: 811,
    symbol: 'ATVI',
    price: 80.51,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
  {
    id: 20,
    date: '03/26/2021',
    execTime: '8:59:09',
    spread: 'Stock',
    side: 'long',
    qty: 570,
    symbol: 'ATVI',
    price: 13.89,
    posEffect: 'To Open',
    edit: null,
    delete: null,
  },
];
